#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  position=top
  height=30
  blur_radius=30
  corner_radius=10
  sticky=off
  padding_left=50
  padding_right=10
  color=$BAR_COLOR
  margin=5
  border_color=0x2fffffff
  border_width=1
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
sketchybar --default \
                     padding_left=5                   \
                     padding_right=5                  \
                     icon.color=$WHITE                \
                     label.padding_right=10           \
                     label.padding_left=10            \
                     #background.color=0xff000000      \
                     background.color=$ITEM_BG_COLOR  \
                     background.corner_radius=5       \
                     background.height=24             \

# --- Left Side Items ---
source $ITEM_DIR/apple.sh

# --- Right Side Items ---

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh

sketchybar --update
